// angularapp/src/app/usermanager/usermanager.component.ts
import { Component, OnInit } from '@angular/core';


type User = {
  id : number;
  fname : string;
  lname : string;
  email : string;
}
const ex1 : User = {
  id: 1,
  fname: "John",
  lname: "Snow",
  email: "jsnow@acmuic.org"
};
const ex2 : User = {
  id: 2,
  fname: "Christian",
  lname: "Bingman",
  email: "cbingm@acmiuc.org"
};

@Component({
  selector: 'app-usermanager',
  templateUrl: './usermanager.component.html',
  styleUrls: ['./usermanager.component.scss']
})

export class UsermanagerComponent implements OnInit {

  userList : User[] = [ex1,ex2];
  isSearching : boolean = false;
  searchList : User[] = [];

  constructor() { }

  ngOnInit(): void {

  }

  onDelete(id : number){
    this.userList = this.userList.filter(el => el.id != id);
  }

  onCreate(fname : string, lname : string, email : string){
    this.userList.push({id: this.userList.length == 0 ? 1 : this.userList[this.userList.length-1].id+1, fname: fname, lname: lname, email: email})
  }

  onSearch(event: any){
    if(event.target.value != ''){
      this.isSearching = true;
      this.searchList = this.userList.filter(el => el.email.includes(event.target.value));
    } else {
      this.isSearching = false;
    }
  }

}

<div class="mx-auto input-group" style="text-align: center;">
    <input type="search" name="search" id="search" class="form-control" placeholder="Search Here!" (input)="onSearch($event);">
</div>
<div class="input-group mx-auto my-3">
    <input type="text" name="fname" id="fname" class="form-control" placeholder="First Name" #fnameField>
    <input type="text" name="lname" id="lname" class="form-control" placeholder="Last Name" #lnameField>
    <input type="email" name="email" id="email" class="form-control" placeholder="E-Mail" #emailField>
    <div class="input-group-append">
        <button class="btn btn-outline-success" (click)='onCreate(fnameField.value, lnameField.value, emailField.value);'>Create User</button>
    </div>
    
</div>
<hr>
<div id="user-list" *ngIf="!isSearching">
    <div class="card my-3" *ngFor="let user of userList">
        <div class="card-body">
            <h5 class="card-title">{{user.fname}} {{user.lname}}</h5>
            <p class="card-text d-inline-block">{{user.id}}</p>
            <p class="card-text float-right">{{user.email}}</p>
        </div>
        <div class="card-footer">
            <div class="float-right">
                <button class="btn btn-outline-danger" (click)="onDelete(user.id);">Delete</button>
            </div>
        </div>
    </div>
</div>
<div id="user-list" *ngIf="isSearching">
    <div class="card my-3" *ngFor="let user of searchList">
        <div class="card-body">
            <h5 class="card-title">{{user.fname}} {{user.lname}}</h5>
            <p class="card-text d-inline-block">{{user.id}}</p>
            <p class="card-text float-right">{{user.email}}</p>
        </div>
        <div class="card-footer">
            <div class="float-right">
                <button class="btn btn-outline-danger" (click)="onDelete(user.id);">Delete</button>
            </div>
        </div>
    </div>
</div>

// vueapp/src/components/usermanager.vue
<template>
  <div class="usermanager">
    <div class="mx-auto input-group" style="text-align: center;">
        <input v-model="searchField" v-on:input="onSearch();" type="search" name="search" id="search" class="form-control" placeholder="Search Here!">
    </div>
    <div class="input-group mx-auto my-3">
        <input v-model="fnameField" type="text" name="fname" id="fname" class="form-control" placeholder="First Name">
        <input v-model="lnameField" type="text" name="lname" id="lname" class="form-control" placeholder="Last Name">
        <input v-model="emailField" type="email" name="email" id="email" class="form-control" placeholder="E-Mail">
        <div class="input-group-append">
            <button class="btn btn-outline-success" v-on:click="onCreate();">Create User</button>
        </div>
        
    </div>
    <hr>
    <div id="user-list" v-if="!isSearching">
        <div class="card my-3" v-for="user in userList" :key="user.id">
            <div class="card-body">
                <h5 class="card-title">{{user.fname}} {{user.lname}}</h5>
                <p class="card-text d-inline-block">{{user.id}}</p>
                <p class="card-text float-right">{{user.email}}</p>
            </div>
            <div class="card-footer">
                <div class="float-right">
                    <button class="btn btn-outline-danger" v-on:click="onDelete(user.id);">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <div id="user-list" v-else>
        <div class="card my-3" v-for="user in searchList" :key="user.id">
            <div class="card-body">
                <h5 class="card-title">{{user.fname}} {{user.lname}}</h5>
                <p class="card-text d-inline-block">{{user.id}}</p>
                <p class="card-text float-right">{{user.email}}</p>
            </div>
            <div class="card-footer">
                <div class="float-right">
                    <button class="btn btn-outline-danger" v-on:click="onDelete(user.id);">Delete</button>
                </div>
            </div>
        </div>
    </div>
  </div>
</template>

<script>
function User(id, fname, lname, email){
    this.id = id;
    this.fname = fname;
    this.lname = lname;
    this.email = email;
}



export default {
  name: 'usermanager',
  data: function (){
    return {
      userList: [new User(1, "John", "Snow", "jsnow@acmuic.org"),new User(2, "Christian", "Bingman", "cbingm@acmuic.org")],
      searchList: [],
      isSearching: false,
      searchField: '',
      fnameField: '',
      lnameField: '',
      emailField: ''
    }
  },
  methods: {
    onDelete: function (id) {
      this.userList = this.userList.filter(el => el.id != id);
    },
    onCreate: function () {
      this.userList.push(new User(this.userList.length == 0 ? 1 : this.userList[this.userList.length-1].id + 1, this.fnameField, this.lnameField, this.emailField))
    },
    onSearch: function () {
      if(this.searchField != ''){
        this.isSearching = true;
        this.searchList = this.userList.filter(el => el.email.includes(this.searchField));
      }else{
        this.isSearching = false;
      }
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
